### PR TITLE
Add formatter configuration option for disabling glyphs

### PR DESCRIPTION
**Pull request by billy-yoyo**
# Context
Implementing this issue: https://github.com/uiua-lang/uiua/issues/60

Adds a `DisableGlyphs` flag to the `.fmt.ua` format configuration. If this is set to true, all glyphs will be converted back to their ascii representations. The formatter will also try to add spacing to make the names clearer when this is enabled.

### CODE REVIEW

**Comment by kaikalii** [comment]
What is the motivation for this?

**Comment by billy-yoyo** [comment]
The issue I linked - if people find keeping track of what the glyphs mean confusing this allows them to write functions by name and keep track of them better.

**Comment by kaikalii** [comment]
I think writing code this way, and having unformatted code in general, is actually something I don't want to encourage.
Having unformatted names leaves code open to breakage when new built-in functions are added, and not reading the glyphs could prevent you from having to learn them.
I'm sorry I left that issue open.

**Comment by billy-yoyo** [comment]
Fair enough, no problem!

**Pull request closed without merging**
