### PR TITLE
update the tour

### PR DESCRIPTION
**Pull request by Marcos-cat**

### CODE REVIEW

**Comment by kaikalii** [comment]
I'm not sure modifiers should be added to some of this code.

Although it raises a question about whether things like `on`/`by` (and maybe `below`) should be taught earlier in the tour/tutorial.

**Comment by Marcos-cat** [comment]
My opinion was that, Because the code got more complicated as it went down, `by` was not the most complicated thing they would encounter so was fine to include.

**Comment by Marcos-cat** [comment]
I don’t think they should be taught, but showing them in later examples seemed harmless

**Comment by Marcos-cat** [comment]
abandoning this until we talk about it further

**Pull request closed without merging**
