### PR TITLE
Add "Median"  uiuism

### PR DESCRIPTION
**Pull request by bkDJ**

### CODE REVIEW

**Comment by kaikalii** [comment]
Thanks for this!
I think maybe `÷2/+⊏⊟⊃⌊⌈÷2-1⧻.` would be preferable?

**Comment by bkDJ** [comment]
* Your proposal would only work with pre-sorted input, which is why mine selects from a `⍏` first.
* Your proposal raises an error with empty input, but since the other aggregating Uiuisms return `NaN` for that edge case, I wrote this PR to have the same behavior. An array's median should be identical to its arithmetic mean if there are 0, 1, or 2 elements.

What do you think?

**Comment by kaikalii** [comment]
Ah, then perhaps `÷2/+⊏⊟⊃⌊⌈÷2-1⧻⟜(⊏⍏.)`.
I don't think empty should return `NaN`. It should error.

**Comment by bkDJ** [comment]
The latest commit should make it ok 🙂

**Pull request merged**
