### PR TITLE
Make un&ae automatically resample audio, some changes to soothe clippy::pedantic

### PR DESCRIPTION
**Pull request by yanqui-uxo**
See #526

### CODE REVIEW

**Comment by kaikalii** [comment]
Like I said [here](https://github.com/uiua-lang/uiua/issues/526#issuecomment-2226999842), I don't think this should be done automatically.
I'd prefer `&ae`/`un &ae` to take/return a sample rate.
You could then take the ratio of that sample rate to `&asr`, and use `keep` to resample.
This would also allow the user to encode audio at different sample rates.

**Comment by kaikalii** [comment]
Some new `keep` functionality allows non-integer scalar counts, for scaling arrays.

**Comment by yanqui-uxo** [comment]
I see! Alright, I'll work on your suggestion. Thanks!

**Comment by kaikalii** [comment]
If you do, I think the argument order for `&ae` should be `Format SampleRate SampleData`

**Pull request closed without merging**
